### ISSUE TITLE
app crashes after uploading image from gallery!

### ISSUE THREAD

**Issue by 08Thug** [Instabug/instabug-cordova#100] opened 2020-07-05 13:41 UTC
After implementing instabug in ionic i did several testing it was working fine untill i tried to upload a image from gallery.
It also worked fine but after uploading image greater than 3 -10 mb, I tried to view it by pressing the image which i uploaded and  then the  application crashed,even thought app crashed in most of the devices but worked good in few devices!

**Comment by alyezz** [comment] 2020-07-07 08:38
@08Thug Thanks for reporting this! can you please share with us the full stack trace of the crash?

**Comment by 08Thug** [comment] 2020-07-07 10:22
i've told you the scenario to reproduce this issue,could you try that way even this issue exist in latest version..
I dont have any crash report! the device which i used for testing belongs to android version 5,6 & 9 . could please fastract this issue.

**Comment by 08Thug** [comment] 2020-07-10 08:29
@alyezz  you there any progress in this issue!?

**Comment by 08Thug** [comment] 2020-07-14 06:07
@alyezz  we are paying for your service yet we cant even get a proper responce highly disappointed!

**Comment by alyezz** [comment] 2020-07-14 11:32
@08Thug I apologize for the delay, i'm looking into this now

**Comment by alyezz** [comment] 2020-07-14 15:07
@08Thug We were able to reproduce and pinpoint the issue, we are currently working on a fix. I will update you on this thread once the issue is resolved.

Thanks for your patience

**Comment by alyezz** [comment] 2020-07-21 09:21
@08Thug  The issue has been fixed and will be included in our next release. In the meantime here is a custom build with the fix that you can use `cordova plugin add https://github.com/Instabug/instabug-cordova.git#custom_build/9.1.6.2`

Feel free to re-open this if you are still facing this issue

**Closed by alyezz** 2020-07-21 09:21 UTC
