### ISSUE TITLE
issue with initialization

### ISSUE THREAD

**Issue by garyocampo** [Instabug/instabug-cordova#30] opened 2017-08-09 18:56 UTC
so, i have installed the plugin with cordova in my app (ionic v1) 
changed what neded to be changed
`<uses-permission android:name="com.instabug.cordova.plugin.MyApplication" />`

and

` public void onCreate()
    {
        new Instabug.Builder(
                this,
                "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                InstabugInvocationEvent.FLOATING_BUTTON
        ).setFloatingButtonEdge(InstabugFloatingButtonEdge.LEFT).setFloatingButtonOffsetFromTop(250).build();
        Instabug.setPrimaryColor(Color.parseColor("#1D82DC"));
        super.onCreate();
    }
`

when i deploy my app on a samsung galaxy s3 android 4.4 the button doesn't appear. there are no errors on my console and code seems alright.
any idea?

**Comment by salmatarzi** [comment] 2017-08-10 12:19
Hi @garyocampo, you should add this line ```android:name="com.instabug.cordova.plugin.MyApplication"``` under the application tag like this, ```<application
     android:name="com.instabug.cordova.plugin.MyApplication"``` not as a permission tag.

**Comment by garyocampo** [comment] 2017-08-11 16:17
Thank for your reply, i still cannot activate the plugin on the phone. I've followed the steps and still.. What information do you need to help me fix it.

**Comment by salmatarzi** [comment] 2017-08-16 12:12
@garyocampo Would it be possible to show me a screenshot of how the manifest file looks like?

**Comment by randaelbaz** [comment] 2017-08-27 07:29
@garyocampo  Hi  Any updates regarding the screenshot of how the manifest file looks like? or did you successfully activate the plugin on the phone?
I’ll close this for now but feel free to re-open it if the issue is still there.

**Closed** 2017-08-27 07:40 UTC
